platform :ios, '10.0'
inhibit_all_warnings!

target 'USEChainWallet' do
 use_frameworks!

pod 'YYCategories'
#pod 'YTKNetwork'
pod 'MBProgressHUD', '~>0.9.1'
pod 'AFNetworking', '~>3.0'

pod 'SnapKit'
pod 'SwipeMenuViewController'
pod 'TangramKit'

end
